### ISSUE TITLE
What's the function of "generate_missing_value_data_sets.py"?

### ISSUE THREAD

**Issue by Mrxuefei** [jmftrindade/6.830-project#1]
Hi,I am trying to do "Complete a Database" project.I have some confusion when I study your codes.
In "generate_missing_value_data_sets.py",you insert many NANs into dataset and generate "*_training.csv "and "*_test.csv" , but in “run_ml_algos.py”  you write a function "read_dataframe_without_na_from_csv" to drop rows with NAN.If I run the “run_ml_algos.py” with ”*.csv“ ，then it has any relation with  "generate_missing_value_data_sets.py".If I run the “run_ml_algos.py” with ”*_training.csv“, "read_dataframe_without_na_from_csv"  will drop all rows.
So I wonder whether "generate_missing_value_data_sets.py" has any function in your project?
![tim 20171225003227](https://user-images.githubusercontent.com/26349122/34327879-3412a586-e90b-11e7-8a35-f9a10bf193e8.png)

**Comment by jmftrindade** [comment]
Hi there.  Yes, that script is deprecated.  In the final version we opted for building a prediction model with no missing values on the features, and assuming the entire dependent variable is "missing".  This is because the goal was to measure how effective an ML-based approach can be at filling missing values.  So inserting missing values on the features (what the generate_missing_value_data_sets.py script was doing) is a little orthogonal, as it can only lower the final accuracy.  For the original question, the answer was somewhat expected: it depends on which column is the dependent variable, and how predictive the features are of it.  So nothing spectacular here, aside from the "time to train" numbers, which consistently showed random forests are a lot faster to train and yield the best accuracy as well :)

Is this "Complete a Database" project something you're doing for school or for fun?  If you want I can discuss some future work ideas with you, e.g., things you can try that I didn't have the time to play with.  I'd advise you not do the exact same thing for a class project by copy-pasting our code, however, as in most schools that would be considered plagiarism.  Also, I should remind you that this repo has no license: https://stackoverflow.com/questions/5521080/can-i-use-the-code-in-a-github-project-which-does-not-have-a-license-specified

**Comment by Mrxuefei** [comment]
Hi.At that time I was doing a course project.Finally I used
following  strategy：
1.Generate some missing values in a column.
2.Filling them by some basic operations such as：mean values or medium
values.
3.Training ML models and do grid search.
And thank you for reminding about license.I didn't do "copy and paste"
thing, I just wanted to know your strategy(or mind map) to do such
a task.Still thanks.

2018-02-21 4:26 GMT+08:00 Joana Trindade <notifications@github.com>:
